apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 34.67.60.39-tls
spec:
  secretName: "34.67.60.39"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "34.67.60.39"
  dnsNames:
    - "34.67.60.39"
    - www.34.67.60.39
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - "34.67.60.39" 
          - www.34.67.60.39
