apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: amanat-xyz-tls
spec:
  secretName: amanat-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: amanat.xyz
  dnsNames:
    - amanat.xyz
    - www.amanat.xyz
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - amanat.xyz
          - www.amanat.xyz